// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt05ClNK4vjj2SaUx1XPX3SetcufxnfHc',
    appId: '1:776473703039:web:8d45958b102e6c06d4454a',
    messagingSenderId: '776473703039',
    projectId: 'medical-31bb1',
    authDomain: 'medical-31bb1.firebaseapp.com',
    storageBucket: 'medical-31bb1.appspot.com',
    measurementId: 'G-XK0WPD5GJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCIPxx8cLT7O_JYDbLjBT11Y_rGqYOQwA',
    appId: '1:776473703039:android:d1c62af0a2ded6f3d4454a',
    messagingSenderId: '776473703039',
    projectId: 'medical-31bb1',
    storageBucket: 'medical-31bb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO0VE0Bcwv4JUxWKQEELHBwTKbI3k35MA',
    appId: '1:776473703039:ios:6cb2a52eaf33df8dd4454a',
    messagingSenderId: '776473703039',
    projectId: 'medical-31bb1',
    storageBucket: 'medical-31bb1.appspot.com',
    iosClientId: '776473703039-35t1i709gu982em274l1vpvj3aa9uddr.apps.googleusercontent.com',
    iosBundleId: 'com.example.medical1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO0VE0Bcwv4JUxWKQEELHBwTKbI3k35MA',
    appId: '1:776473703039:ios:6cb2a52eaf33df8dd4454a',
    messagingSenderId: '776473703039',
    projectId: 'medical-31bb1',
    storageBucket: 'medical-31bb1.appspot.com',
    iosClientId: '776473703039-35t1i709gu982em274l1vpvj3aa9uddr.apps.googleusercontent.com',
    iosBundleId: 'com.example.medical1',
  );
}
